"""
RegimeX AI Research — Domain Models
===================================
Domain entities and value objects for the grounded market research assistant.
Pure Python, strictly decoupled from transport frameworks and web protocols.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class ResearchIntent(StrEnum):
    """Classified research intent directing deterministic retrieval."""

    MARKET_OVERVIEW = "MARKET_OVERVIEW"
    CURRENT_REGIME = "CURRENT_REGIME"
    REGIME_ANALYTICS = "REGIME_ANALYTICS"
    TRANSITIONS = "TRANSITIONS"
    RISK = "RISK"
    BACKTEST = "BACKTEST"
    METHODOLOGY = "METHODOLOGY"
    COMPARISON = "COMPARISON"
    MODEL_EXPLANATION = "MODEL_EXPLANATION"
    PREDICTION_REFUSAL = "PREDICTION_REFUSAL"
    ADVICE_REFUSAL = "ADVICE_REFUSAL"
    UNSUPPORTED = "UNSUPPORTED"


class EvidencePacket(BaseModel):
    """
    Deterministic factual evidence packet retrieved from RegimeX domain engines.

    Every factual claim generated by the assistant must be grounded in and
    traceable to one or more EvidencePackets.
    """

    model_config = ConfigDict(frozen=True)

    source_id: str = Field(
        ...,
        description="Canonical source identifier, e.g. 'regime:SPY:current' or 'risk:SPY'",
    )
    source_type: str = Field(
        ...,
        description=(
            "Domain source type: 'market' | 'regime' | 'regime_transition' "
            "| 'risk' | 'backtest' | 'methodology'"
        ),
    )
    title: str = Field(..., description="Human-readable title describing the evidence context")
    facts: dict[str, Any] = Field(
        default_factory=dict,
        description="Key-value pairs of verified quantitative facts and analytics",
    )
    timestamp: str | None = Field(
        default=None,
        description="Observation or computation timestamp in ISO 8601 UTC format",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional technical provenance details (model name, version, algorithm)",
    )


class Citation(BaseModel):
    """
    Explicit citation linking an assistant statement to its backing evidence packet.
    """

    model_config = ConfigDict(frozen=True)

    id: int = Field(..., ge=1, description="Numeric citation marker, e.g. 1 for [1]")
    source_id: str = Field(..., description="Referenced EvidencePacket source_id")
    source_type: str = Field(..., description="Referenced evidence source type")
    title: str = Field(..., description="Citation title for display")
    symbol: str | None = Field(default=None, description="Associated instrument ticker symbol")
    timestamp: str | None = Field(default=None, description="Evidence observation timestamp")
    model: str | None = Field(default=None, description="Analytical model name and version")
    facts_summary: str | None = Field(
        default=None, description="Concise synopsis of cited factual metrics"
    )
    details: dict[str, Any] = Field(
        default_factory=dict,
        description="Auditable metadata dictionary for the evidence panel",
    )


class ResearchQuery(BaseModel):
    """
    Validated user question and scoping parameters submitted to the research assistant.
    """

    model_config = ConfigDict(frozen=True)

    question: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="User research question",
    )
    symbol: str | None = Field(
        default=None,
        max_length=20,
        description="Optional explicit instrument symbol scope (e.g. 'SPY')",
    )
    conversation_id: str | None = Field(
        default=None,
        max_length=100,
        description="Optional client conversation tracking identifier",
    )
    context: dict[str, Any] | None = Field(
        default=None,
        description="Optional client state context",
    )
    stream: bool = Field(
        default=False,
        description="Whether to stream the response as Server-Sent Events",
    )

    @field_validator("question")
    @classmethod
    def validate_question(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("Research question cannot be empty or whitespace only.")
        return cleaned

    @field_validator("symbol")
    @classmethod
    def validate_symbol(cls, value: str | None) -> str | None:
        if value is None:
            return None
        cleaned = value.strip().upper()
        return cleaned if cleaned else None


class ResearchResponse(BaseModel):
    """
    Validated research response containing grounded text, citations, and evidence provenance.
    """

    model_config = ConfigDict(frozen=True)

    answer: str = Field(..., description="Grounded quantitative explanation")
    citations: list[Citation] = Field(
        default_factory=list,
        description="Citations supporting factual statements in the answer",
    )
    evidence: list[EvidencePacket] = Field(
        default_factory=list,
        description="Supplied evidence packets used for grounding",
    )
    model: str = Field(..., description="AI model or provider that generated the response")
    generated_at: str = Field(..., description="ISO 8601 UTC generation timestamp")
    request_id: str = Field(..., description="Request correlation identifier")
    intent: ResearchIntent = Field(..., description="Classified query intent")
    symbol: str | None = Field(default=None, description="Resolved instrument symbol")


class ResearchStreamEvent(BaseModel):
    """
    Typed event payload emitted during SSE streaming.
    """

    model_config = ConfigDict(frozen=True)

    event: str = Field(
        ...,
        description=(
            "Event kind: 'metadata' | 'evidence' | 'token' | 'citation' | 'complete' | 'error'"
        ),
    )
    data: dict[str, Any] = Field(default_factory=dict, description="Event payload dictionary")
