"""
RegimeX Backtesting Module
==========================
Event-driven backtesting engine with point-in-time sequential simulation,
realistic transaction costs (slippage and commissions), portfolio accounting,
deterministic strategy comparison analytics, and seamless integration with
the V13 Portfolio Risk Engine.
"""

from app.modules.backtesting.domain.errors import (
    BacktestingError,
    ComparisonError,
    DuplicateStrategyIdError,
    EmptyComparisonError,
    ExecutionError,
    IncompatibleEvaluationPeriodError,
    InsufficientComparisonDataError,
    InsufficientFundsError,
    InsufficientPositionError,
    InvalidEquityError,
    InvalidEventError,
    InvalidMarketDataError,
    InvalidOrderError,
    InvalidReportError,
    InvalidStrategyIdError,
    LookaheadBiasError,
    NonFiniteValueError,
    ReportError,
    TemporalOrderError,
)
from app.modules.backtesting.domain.interfaces import (
    BacktestEngineProtocol,
    ExecutionModelProtocol,
    PerformanceReportBuilderProtocol,
    Strategy,
    StrategyComparisonEngineProtocol,
    StrategyContext,
)
from app.modules.backtesting.domain.models import (
    REPORT_SCHEMA_VERSION,
    BacktestConfig,
    BacktestResult,
    ComparisonPeriod,
    EquitySnapshot,
    EventType,
    ExecutionPriceConvention,
    FillEvent,
    MarketEvent,
    Methodology,
    MetricDefinition,
    MetricDirectionSemantics,
    OrderRequest,
    OrderSide,
    OrderType,
    PairwiseComparison,
    PerformanceReport,
    Position,
    ReportMetadata,
    SignalEvent,
    StrategyComparisonInput,
    StrategyComparisonResult,
    StrategySummary,
    TradeStatistics,
)
from app.modules.backtesting.infrastructure.comparison import StrategyComparisonEngine
from app.modules.backtesting.infrastructure.engine import (
    EventDrivenBacktestEngine,
    StrategyContextImpl,
)
from app.modules.backtesting.infrastructure.execution import SimulatedExecutionModel
from app.modules.backtesting.infrastructure.portfolio import SimulatedPortfolio
from app.modules.backtesting.infrastructure.reporting import (
    DEFAULT_LIMITATIONS,
    DEFAULT_METHODOLOGY,
    DEFAULT_METRIC_DEFINITIONS,
    PerformanceReportBuilder,
)

__all__ = [
    "BacktestConfig",
    "BacktestEngineProtocol",
    "BacktestResult",
    "BacktestingError",
    "ComparisonError",
    "ComparisonPeriod",
    "DEFAULT_LIMITATIONS",
    "DEFAULT_METHODOLOGY",
    "DEFAULT_METRIC_DEFINITIONS",
    "DuplicateStrategyIdError",
    "EmptyComparisonError",
    "EquitySnapshot",
    "EventType",
    "EventDrivenBacktestEngine",
    "ExecutionError",
    "ExecutionModelProtocol",
    "ExecutionPriceConvention",
    "FillEvent",
    "IncompatibleEvaluationPeriodError",
    "InsufficientComparisonDataError",
    "InsufficientFundsError",
    "InsufficientPositionError",
    "InvalidEquityError",
    "InvalidEventError",
    "InvalidMarketDataError",
    "InvalidOrderError",
    "InvalidReportError",
    "InvalidStrategyIdError",
    "LookaheadBiasError",
    "MarketEvent",
    "Methodology",
    "MetricDefinition",
    "MetricDirectionSemantics",
    "NonFiniteValueError",
    "OrderRequest",
    "OrderSide",
    "OrderType",
    "PairwiseComparison",
    "PerformanceReport",
    "PerformanceReportBuilder",
    "PerformanceReportBuilderProtocol",
    "Position",
    "REPORT_SCHEMA_VERSION",
    "ReportError",
    "ReportMetadata",
    "SignalEvent",
    "SimulatedExecutionModel",
    "SimulatedPortfolio",
    "Strategy",
    "StrategyComparisonEngine",
    "StrategyComparisonEngineProtocol",
    "StrategyComparisonInput",
    "StrategyComparisonResult",
    "StrategyContext",
    "StrategyContextImpl",
    "StrategySummary",
    "TemporalOrderError",
    "TradeStatistics",
]
